### ISSUE TITLE
[Windows] Ctrl + C does not kill properly timeflux anymore

### ISSUE THREAD

**Issue by morganOmind** [timeflux/timeflux#10]
It is pretty annoying, because now we have to systematically close the terminal to kill timeflux, then re-open a new one, activate the conda env, move to the correct folder then re-launch timeflux !

**Comment by mesca** [comment]
Did you upgrade Timeflux and all the plugins? This should have been fixed by now. If the problem persists, please forward me the graph, as there is probably a blocking thread that is not released properly in one of the nodes you use.

**Comment by morganOmind** [comment]
'taskkill /IM /F python.exe' works but is not ideal ;)

**Comment by morganOmind** [comment]
yes I just updated, the used graph is : https://github.com/OpenMindInnovation/timeflux_omind/blob/master/test/graphs/hyperscanning_respi_replay.yaml

**Comment by mesca** [comment]
Any error message?

**Comment by morganOmind** [comment]
Traceback (most recent call last):
  File "C:\Users\Morgan\AppData\Local\conda\conda\envs\timeflux\lib\site-packages\psutil\_pswindows.py", line 894, in wait
    exit_code = cext.proc_wait(self.pid, cext_timeout)
_psutil_windows.TimeoutExpired: WaitForSingleObject() returned WAIT_TIMEOUT

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "timeflux.py", line 4, in <module>
    if __name__ == '__main__': main()
  File "D:\Omind\timeflux\timeflux\timeflux.py", line 27, in main
    _terminate()
  File "D:\Omind\timeflux\timeflux\timeflux.py", line 39, in _terminate
    psutil.wait_procs(psutil.Process().children())
  File "C:\Users\Morgan\AppData\Local\conda\conda\envs\timeflux\lib\site-packages\psutil\__init__.py", line 1669, in wait_procs
    check_gone(proc, max_timeout)
  File "C:\Users\Morgan\AppData\Local\conda\conda\envs\timeflux\lib\site-packages\psutil\__init__.py", line 1632, in check_gone
    returncode = proc.wait(timeout=timeout)
  File "C:\Users\Morgan\AppData\Local\conda\conda\envs\timeflux\lib\site-packages\psutil\__init__.py", line 1384, in wait
    return self._proc.wait(timeout)
  File "C:\Users\Morgan\AppData\Local\conda\conda\envs\timeflux\lib\site-packages\psutil\_pswindows.py", line 716, in wrapper
    return fun(self, *args, **kwargs)
  File "C:\Users\Morgan\AppData\Local\conda\conda\envs\timeflux\lib\site-packages\psutil\_pswindows.py", line 894, in wait
    exit_code = cext.proc_wait(self.pid, cext_timeout)
KeyboardInterrupt

**Comment by morganOmind** [comment]
`Traceback (most recent call last):
  File "C:\Users\Morgan\AppData\Local\conda\conda\envs\timeflux\lib\site-packages\psutil\_pswindows.py", line 894, in wait
    exit_code = cext.proc_wait(self.pid, cext_timeout)
_psutil_windows.TimeoutExpired: WaitForSingleObject() returned WAIT_TIMEOUT

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "timeflux.py", line 4, in <module>
    if __name__ == '__main__': main()
  File "D:\Omind\timeflux\timeflux\timeflux.py", line 27, in main
    _terminate()
  File "D:\Omind\timeflux\timeflux\timeflux.py", line 39, in _terminate
    psutil.wait_procs(psutil.Process().children())
  File "C:\Users\Morgan\AppData\Local\conda\conda\envs\timeflux\lib\site-packages\psutil\__init__.py", line 1669, in wait_procs
    check_gone(proc, max_timeout)
  File "C:\Users\Morgan\AppData\Local\conda\conda\envs\timeflux\lib\site-packages\psutil\__init__.py", line 1632, in check_gone
    returncode = proc.wait(timeout=timeout)
  File "C:\Users\Morgan\AppData\Local\conda\conda\envs\timeflux\lib\site-packages\psutil\__init__.py", line 1384, in wait
    return self._proc.wait(timeout)
  File "C:\Users\Morgan\AppData\Local\conda\conda\envs\timeflux\lib\site-packages\psutil\_pswindows.py", line 716, in wrapper
    return fun(self, *args, **kwargs)
  File "C:\Users\Morgan\AppData\Local\conda\conda\envs\timeflux\lib\site-packages\psutil\_pswindows.py", line 894, in wait
    exit_code = cext.proc_wait(self.pid, cext_timeout)
KeyboardInterrupt`

**Comment by mesca** [comment]
Does [this](https://github.com/timeflux/timeflux/commit/17d6006a513125085380235a5d79dc93e34e2467) fix your issue?

**Comment by morganOmind** [comment]
yes it works, thanks @mesca  (just a lag of ~10s before timeflux actually stops)

**Comment by mesca** [comment]
Yes, there is some cleanup being performed. For some reason, one of the node hangs on termination (probably because of a blocking thread, will need to investigate where it happens precisely).
