### ISSUE TITLE
Timeflux fails on fresh installl

### ISSUE THREAD

**Issue by gael-vanderlee** [timeflux/timeflux#83]
I've tried installing timeflux on 2 different machines, Windows and MacOS, using different virtual environment managers, different python version and different timeflux versions. However, when it installs properly, it fails to initialize with the following error:

```
(project-py3.10) C:\Users\\PycharmProjects\project>timeflux
Traceback (most recent call last):
  File "C:\Users\\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\\AppData\Local\pypoetry\Cache\virtualenvs\project-XiRr8lx2-py3.10\Scripts\timeflux.exe\__main__.py", line 4, in <module>
  File "C:\Users\\AppData\Local\pypoetry\Cache\virtualenvs\project-XiRr8lx2-py3.10\lib\site-packages\timeflux\timeflux.py", line 11, in <module>
    from timeflux.core.manager import Manager
  File "C:\Users\\AppData\Local\pypoetry\Cache\virtualenvs\project-XiRr8lx2-py3.10\lib\site-packages\timeflux\core\manager.py", line 12, in <module>
    from timeflux.core.worker import Worker
  File "C:\Users\\AppData\Local\pypoetry\Cache\virtualenvs\project-XiRr8lx2-py3.10\lib\site-packages\timeflux\core\worker.py", line 8, in <module>
    from timeflux.core.graph import Graph
  File "C:\Users\\AppData\Local\pypoetry\Cache\virtualenvs\project-XiRr8lx2-py3.10\lib\site-packages\timeflux\core\graph.py", line 3, in <module>
    import networkx as nx
  File "C:\Users\\AppData\Local\pypoetry\Cache\virtualenvs\project-XiRr8lx2-py3.10\lib\site-packages\networkx\__init__.py", line 64, in <module>
    import networkx.readwrite
  File "C:\Users\\AppData\Local\pypoetry\Cache\virtualenvs\project-XiRr8lx2-py3.10\lib\site-packages\networkx\readwrite\__init__.py", line 15, in <module>
    from networkx.readwrite.graphml import *
  File "C:\Users\\AppData\Local\pypoetry\Cache\virtualenvs\project-XiRr8lx2-py3.10\lib\site-packages\networkx\readwrite\graphml.py", line 344, in <module>
    class GraphML:
  File "C:\Users\\AppData\Local\pypoetry\Cache\virtualenvs\project-XiRr8lx2-py3.10\lib\site-packages\networkx\readwrite\graphml.py", line 377, in GraphML
    (np.float_, "float"),
  File "C:\Users\\AppData\Local\pypoetry\Cache\virtualenvs\project-XiRr8lx2-py3.10\lib\site-packages\numpy\__init__.py", line 413, in __getattr__
    raise AttributeError(
AttributeError: `np.float_` was removed in the NumPy 2.0 release. Use `np.float64` instead.
```

I attempted to downgrade numpy but it did not solve the problem.

**Comment by mesca** [comment]
This is a known issue that will be fixed in the next release.
I had locked NumPy and NetworkX versions, but I forgot to release the PyPi package. I published a new version just now.
Please retry with version 0.17.2 (in a new conda environment) and let me know.

**Comment by gael-vanderlee** [comment]
It's fixed ! Thanks a lot for the quick reaction.
